# A.R.C. v6 - Scaled Baseline

This notebook builds upon the highly successful `v3` baseline (which scored 84% on local validation and 41 on Kaggle) by implementing the following strategic enhancements derived from top-tier AIMO solutions:

1. **Scaled Test-Time Compute:** Increased parallel attempts from `8` to `16` to cast a wider search net.
2. **Dynamic Early Stopping:** Increased the early stopping threshold from `4` to `6` to maintain high confidence in the face of increased sampling.
3. **Tool-Integrated Brute Force:** Modified the `preference_prompt` to strongly emphasize writing Python brute-force/search loops when analytical methods stall, ensuring exact integer outputs.

In [7]:
%pip uninstall --yes 'keras' 'matplotlib' 'scikit-learn' 'tensorflow'

WARNING: Ignoring invalid distribution ~ransformers (/usr/local/lib/python3.12/dist-packages)
WARNING: Ignoring invalid distribution ~ransformers (/usr/local/lib/python3.12/dist-packages)
WARNING: Skipping keras as it is not installed.
WARNING: Ignoring invalid distribution ~ransformers (/usr/local/lib/python3.12/dist-packages)
WARNING: Skipping matplotlib as it is not installed.
WARNING: Ignoring invalid distribution ~ransformers (/usr/local/lib/python3.12/dist-packages)
WARNING: Skipping scikit-learn as it is not installed.
WARNING: Ignoring invalid distribution ~ransformers (/usr/local/lib/python3.12/dist-packages)
WARNING: Skipping tensorflow as it is not installed.
Note: you may need to restart the kernel to use updated packages.

In [8]:
import warnings
warnings.simplefilter('ignore')

In [9]:
import os
import sys
import subprocess

In [10]:
def set_env(wheels_dir):
    subprocess.run([
        sys.executable, '-m', 'pip', 'install', 
        '--no-index', '--find-links', wheels_dir, 
        'unsloth', 'trl', 'vllm', 'openai_harmony'
    ], check=True)

In [11]:
set_env(wheels_dir='/kaggle/input/datasets/chandan989/arc-aimo-utils/wheels')

WARNING: Ignoring invalid distribution ~ransformers (/usr/local/lib/python3.12/dist-packages)
WARNING: Ignoring invalid distribution ~ransformers (/usr/local/lib/python3.12/dist-packages)

Looking in links: /kaggle/input/datasets/chandan989/arc-aimo-utils/wheels
Processing /kaggle/input/datasets/chandan989/arc-aimo-utils/wheels/unsloth-2025.12.9-py3-none-any.whl
Processing /kaggle/input/datasets/chandan989/arc-aimo-utils/wheels/trl-0.24.0-py3-none-any.whl
Processing /kaggle/input/datasets/chandan989/arc-aimo-utils/wheels/vllm-0.11.2-cp38-abi3-manylinux1_x86_64.whl
Requirement already satisfied: openai_harmony in /usr/local/lib/python3.12/dist-packages (0.0.8)
Processing /kaggle/input/datasets/chandan989/arc-aimo-utils/wheels/unsloth_zoo-2025.12.7-py3-none-any.whl (from unsloth)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.46.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from unsloth) (26.0)
Requirement already satisfied: torch>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.9.0+cu128)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.25.0+cu128)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.0.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.9.5)
Requirement already satisfied: tyro in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.0.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.29.5)
Requirement already satisfied: xformers>=0.0.27.post2 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.0.33.post1)
Processing /kaggle/input/datasets/chandan989/arc-aimo-utils/wheels/bitsandbytes-0.49.0-py3-none-manylinux_2_24_x86_64.whl (from unsloth)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (3.5.0)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.2.1)
Processing /kaggle/input/datasets/chandan989/arc-aimo-utils/wheels/datasets-4.3.0-py3-none-any.whl (from unsloth)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.12.0)
Requirement already satisfied: peft!=0.11.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.18.1)
Requirement already satisfied: huggingface_hub>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.36.0)
Requirement already satisfied: hf_transfer in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.1.9)
Requirement already satisfied: diffusers in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.36.0)
Processing /kaggle/input/datasets/chandan989/arc-aimo-utils/wheels/transformers-4.57.3-py3-none-any.whl (from unsloth)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from vllm) (2025.11.3)
Requirement already satisfied: cachetools in /usr/local/lib/python3.12/dist-packages (from vllm) (6.2.6)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.32.4)
Requirement already satisfied: blake3 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.0.8)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.12/dist-packages (from vllm) (9.0.0)
Requirement already satisfied: tokenizers>=0.21.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.22.2)
Requirement already satisfied: fastapi>=0.115.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (0.133.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from vllm) (3.13.3)
Requirement already satisfied: openai>=1.99.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.23.0)
Requirement already satisfied: pydantic>=2.12.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.12.3)
Requirement already satisfied: prometheus_client>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.24.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from vllm) (11.3.0)
Requirement already satisfied: prometheus-fastapi-instrumentator>=7.0.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (7.1.0)
Requirement already satisfied: tiktoken>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.12.0)
Requirement already satisfied: lm-format-enforcer==0.11.3 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.11.3)
Requirement already satisfied: llguidance<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.3.0)
Requirement already satisfied: outlines_core==0.2.11 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.2.11)
Requirement already satisfied: diskcache==5.6.3 in /usr/local/lib/python3.12/dist-packages (from vllm) (5.6.3)
Requirement already satisfied: lark==1.2.2 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.2.2)
Processing /kaggle/input/datasets/chandan989/arc-aimo-utils/wheels/xgrammar-0.1.25-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from vllm)
Requirement already satisfied: typing_extensions>=4.10 in /usr/local/lib/python3.12/dist-packages (from vllm) (4.15.0)
Requirement already satisfied: filelock>=3.16.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (3.24.3)
Requirement already satisfied: partial-json-parser in /usr/local/lib/python3.12/dist-packages (from vllm) (0.2.1.1.post7)
Requirement already satisfied: pyzmq>=25.0.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (26.2.1)
Requirement already satisfied: msgspec in /usr/local/lib/python3.12/dist-packages (from vllm) (0.20.0)
Requirement already satisfied: gguf>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.17.1)
Processing /kaggle/input/datasets/chandan989/arc-aimo-utils/wheels/mistral_common-1.8.8-py3-none-any.whl (from mistral_common[image]>=1.8.5->vllm)
Requirement already satisfied: opencv-python-headless>=4.11.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (4.13.0.92)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from vllm) (6.0.3)
Requirement already satisfied: six>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.17.0)
Requirement already satisfied: setuptools<81.0.0,>=77.0.3 in /usr/local/lib/python3.12/dist-packages (from vllm) (80.9.0)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from vllm) (0.8.2)
Processing /kaggle/input/datasets/chandan989/arc-aimo-utils/wheels/compressed_tensors-0.12.2-py3-none-any.whl (from vllm)
Requirement already satisfied: depyf==0.20.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.20.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from vllm) (3.1.2)
Requirement already satisfied: watchfiles in /usr/local/lib/python3.12/dist-packages (from vllm) (1.1.1)
Requirement already satisfied: python-json-logger in /usr/local/lib/python3.12/dist-packages (from vllm) (4.0.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from vllm) (1.16.3)
Requirement already satisfied: ninja in /usr/local/lib/python3.12/dist-packages (from vllm) (1.13.0)
Requirement already satisfied: pybase64 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.4.3)
Requirement already satisfied: cbor2 in /usr/local/lib/python3.12/dist-packages (from vllm) (5.7.1)
Requirement already satisfied: setproctitle in /usr/local/lib/python3.12/dist-packages (from vllm) (1.3.7)
Requirement already satisfied: anthropic==0.71.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.71.0)
Processing /kaggle/input/datasets/chandan989/arc-aimo-utils/wheels/model_hosting_container_standards-0.1.12-py3-none-any.whl (from vllm)
Requirement already satisfied: numba==0.61.2 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.61.2)
Requirement already satisfied: ray>=2.48.0 in /usr/local/lib/python3.12/dist-packages (from ray[cgraph]>=2.48.0->vllm) (2.54.0)
Processing /kaggle/input/datasets/chandan989/arc-aimo-utils/wheels/torchaudio-2.9.0+cu128-cp312-cp312-manylinux_2_28_x86_64.whl (from vllm)
Processing /kaggle/input/datasets/chandan989/arc-aimo-utils/wheels/torchvision-0.24.0+cu128-cp312-cp312-manylinux_2_28_x86_64.whl (from unsloth)
Processing /kaggle/input/datasets/chandan989/arc-aimo-utils/wheels/flashinfer_python-0.5.2-py3-none-any.whl (from vllm)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from anthropic==0.71.0->vllm) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from anthropic==0.71.0->vllm) (1.9.0)
Requirement already satisfied: docstring-parser<1,>=0.15 in /usr/local/lib/python3.12/dist-packages (from anthropic==0.71.0->vllm) (0.17.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from anthropic==0.71.0->vllm) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from anthropic==0.71.0->vllm) (0.10.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from anthropic==0.71.0->vllm) (1.3.1)
Requirement already satisfied: loguru in /usr/local/lib/python3.12/dist-packages (from compressed-tensors==0.12.2->vllm) (0.7.3)
Requirement already satisfied: astor in /usr/local/lib/python3.12/dist-packages (from depyf==0.20.0->vllm) (0.8.1)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from depyf==0.20.0->vllm) (0.4.0)
Requirement already satisfied: apache-tvm-ffi<0.2,>=0.1 in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.5.2->vllm) (0.1.7)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.5.2->vllm) (8.3.1)
Requirement already satisfied: nvidia-cudnn-frontend>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.5.2->vllm) (1.17.0)
Requirement already satisfied: nvidia-cutlass-dsl>=4.2.1 in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.5.2->vllm) (4.3.4)
Requirement already satisfied: nvidia-ml-py in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.5.2->vllm) (13.590.48)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.5.2->vllm) (0.9.0)
Requirement already satisfied: interegular>=0.3.2 in /usr/local/lib/python3.12/dist-packages (from lm-format-enforcer==0.11.3->vllm) (0.3.3)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba==0.61.2->vllm) (0.44.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (2025.9.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.13.1.3)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.34.1->unsloth) (0.7.0)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (23.0.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.3.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.70.16)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.115.0->fastapi[standard]>=0.115.0->vllm) (0.52.1)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.115.0->fastapi[standard]>=0.115.0->vllm) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.115.0->fastapi[standard]>=0.115.0->vllm) (0.0.4)
Processing /kaggle/input/datasets/chandan989/arc-aimo-utils/wheels/fastapi_cli-0.0.20-py3-none-any.whl (from fastapi-cli[standard]>=0.0.8; extra == "standard"->fastapi[standard]>=0.115.0->vllm)
Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (0.0.22)
Requirement already satisfied: email-validator>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (2.3.0)
Requirement already satisfied: uvicorn>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.12.0; extra == "standard"->fastapi[standard]>=0.115.0->vllm) (0.41.0)
Requirement already satisfied: pydantic-settings>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (2.13.1)
Requirement already satisfied: pydantic-extra-types>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (2.10.6)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth) (1.3.0)
Requirement already satisfied: jsonschema>=4.21.1 in /usr/local/lib/python3.12/dist-packages (from mistral_common>=1.8.5->mistral_common[image]>=1.8.5->vllm) (4.26.0)
Requirement already satisfied: jmespath in /usr/local/lib/python3.12/dist-packages (from model-hosting-container-standards<1.0.0->vllm) (1.1.0)
Requirement already satisfied: supervisor>=4.2.0 in /usr/local/lib/python3.12/dist-packages (from model-hosting-container-standards<1.0.0->vllm) (4.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.12.0->vllm) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.12.0->vllm) (2.41.4)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ray>=2.48.0->ray[cgraph]>=2.48.0->vllm) (1.1.2)
Requirement already satisfied: cupy-cuda12x in /usr/local/lib/python3.12/dist-packages (from ray[cgraph]>=2.48.0->vllm) (14.0.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (2026.1.4)
Requirement already satisfied: torchao>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2025.12.7->unsloth) (0.15.0+cu128)
Processing /kaggle/input/datasets/chandan989/arc-aimo-utils/wheels/cut_cross_entropy-25.1.1-py3-none-any.whl (from unsloth_zoo>=2025.12.7->unsloth)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->vllm) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->vllm) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->vllm) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->vllm) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->vllm) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->vllm) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->vllm) (1.22.0)
Requirement already satisfied: importlib_metadata in /usr/local/lib/python3.12/dist-packages (from diffusers->unsloth) (8.7.1)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (4.5.1)
Requirement already satisfied: dnspython>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from email-validator>=2.0.0->fastapi[standard]>=0.115.0->vllm) (2.8.0)
Requirement already satisfied: typer>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from fastapi-cli>=0.0.8->fastapi-cli[standard]>=0.0.8; extra == "standard"->fastapi[standard]>=0.115.0->vllm) (0.24.1)
Requirement already satisfied: rich-toolkit>=0.14.8 in /usr/local/lib/python3.12/dist-packages (from fastapi-cli>=0.0.8->fastapi-cli[standard]>=0.0.8; extra == "standard"->fastapi[standard]>=0.115.0->vllm) (0.17.1)
Processing /kaggle/input/datasets/chandan989/arc-aimo-utils/wheels/fastapi_cloud_cli-0.8.0-py3-none-any.whl (from fastapi-cli[standard]>=0.0.8; extra == "standard"->fastapi[standard]>=0.115.0->vllm)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->anthropic==0.71.0->vllm) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.25.0->anthropic==0.71.0->vllm) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.4.0->unsloth) (3.0.3)

WARNING: Ignoring invalid distribution ~ransformers (/usr/local/lib/python3.12/dist-packages)

Installing collected packages: transformers, torchvision, torchaudio, model-hosting-container-standards, flashinfer-python, fastapi-cloud-cli, fastapi-cli, datasets, cut_cross_entropy, bitsandbytes, xgrammar, trl, mistral_common, compressed-tensors, unsloth_zoo, unsloth, vllm
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.25.0+cu128
    Uninstalling torchvision-0.25.0+cu128:

    WARNING: Ignoring invalid distribution ~ransformers (/usr/local/lib/python3.12/dist-packages)

      Successfully uninstalled torchvision-0.25.0+cu128
  Attempting uninstall: torchaudio
    Found existing installation: torchaudio 2.10.0+cu128
    Uninstalling torchaudio-2.10.0+cu128:

    WARNING: Ignoring invalid distribution ~ransformers (/usr/local/lib/python3.12/dist-packages)

      Successfully uninstalled torchaudio-2.10.0+cu128
  Attempting uninstall: datasets
    Found existing installation: datasets 4.8.3
    Uninstalling datasets-4.8.3:
      Successfully uninstalled datasets-4.8.3

    WARNING: Ignoring invalid distribution ~ransformers (/usr/local/lib/python3.12/dist-packages)
WARNING: Ignoring invalid distribution ~ransformers (/usr/local/lib/python3.12/dist-packages)
WARNING: Ignoring invalid distribution ~ransformers (/usr/local/lib/python3.12/dist-packages)
WARNING: Ignoring invalid distribution ~ransformers (/usr/local/lib/python3.12/dist-packages)
WARNING: Ignoring invalid distribution ~ransformers (/usr/local/lib/python3.12/dist-packages)

Successfully installed bitsandbytes-0.49.0 compressed-tensors-0.12.2 cut_cross_entropy-25.1.1 datasets-4.3.0 fastapi-cli-0.0.20 fastapi-cloud-cli-0.8.0 flashinfer-python-0.5.2 mistral_common-1.8.8 model-hosting-container-standards-0.1.12 torchaudio-2.9.0+cu128 torchvision-0.24.0+cu128 transformers trl-0.24.0 unsloth-2025.12.9 unsloth_zoo-2025.12.7 vllm-0.11.2 xgrammar-0.1.25

WARNING: Ignoring invalid distribution ~ransformers (/usr/local/lib/python3.12/dist-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sentence-transformers 5.2.3 requires scikit-learn, which is not installed.
fastai 2.8.7 requires matplotlib, which is not installed.
fastai 2.8.7 requires scikit-learn, which is not installed.

In [12]:
os.environ['TRANSFORMERS_NO_TF'] = '1'
os.environ['TRANSFORMERS_NO_FLAX'] = '1'
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
os.environ['TOKENIZERS_PARALLELISM'] = 'false'
os.environ['TRITON_PTXAS_PATH'] = '/usr/local/cuda/bin/ptxas'
os.environ['TIKTOKEN_ENCODINGS_BASE'] = '/kaggle/input/datasets/chandan989/arc-aimo-utils/tiktoken_encodings'

In [13]:
import gc
import re
import math
import time
import queue
import threading
import contextlib
from typing import Optional
from jupyter_client import KernelManager
from collections import Counter, defaultdict
from concurrent.futures import as_completed, ThreadPoolExecutor

import pandas as pd
import polars as pl

from openai import OpenAI

from openai_harmony import (
    HarmonyEncodingName, 
    load_harmony_encoding, 
    SystemContent, 
    ReasoningEffort, 
    ToolNamespaceConfig, 
    Author, 
    Message, 
    Role, 
    TextContent, 
    Conversation
)

from transformers import set_seed
import kaggle_evaluation.aimo_3_inference_server

In [14]:
class ARCConfig:
    
    system_prompt = (
        'You are an elite mathematical problem solver with expertise at the International '
        'Mathematical Olympiad (IMO) level. Your goal is to find the correct answer through '
        'rigorous mathematical reasoning.\n\n'
        
        '# Problem-Solving Approach:\n'
        '1. UNDERSTAND: Carefully read and rephrase the problem in your own words. '
        'Identify what is given, what needs to be found, and any constraints.\n'
        '2. EXPLORE: Consider multiple solution strategies. Think about relevant theorems, '
        'techniques, patterns, or analogous problems. Don\'t commit to one approach immediately.\n'
        '3. PLAN: Select the most promising approach and outline key steps before executing.\n'
        '4. EXECUTE: Work through your solution methodically. Show all reasoning steps clearly.\n'
        '5. VERIFY: Check your answer by substituting back, testing edge cases, or using '
        'alternative methods. Ensure logical consistency throughout.\n\n'
        
        '# Mathematical Reasoning Principles:\n'
        '- Break complex problems into smaller, manageable sub-problems\n'
        '- Look for patterns, symmetries, and special cases that provide insight\n'
        '- Use concrete examples to build intuition before generalizing\n'
        '- Consider extreme cases and boundary conditions\n'
        '- If stuck, try working backwards from the desired result\n'
        '- Be willing to restart with a different approach if needed\n\n'
        
        '# Verification Requirements:\n'
        '- Cross-check arithmetic and algebraic manipulations\n'
        '- Verify that your solution satisfies all problem constraints\n'
        '- Test your answer with simple cases or special values when possible\n'
        '- Ensure dimensional consistency and reasonableness of the result\n\n'
        
        '# Output Format:\n'
        'The final answer must be a non-negative integer between 0 and 99999.\n'
        'Place your final numerical answer inside \\boxed{}, e.g., \\boxed{42}\n\n'
        
        'Think step-by-step and show your complete reasoning process. Quality of reasoning '
        'is as important as the final answer.'
    )
    
    tool_prompt = (
        'Use this tool to execute Python code for:\n'
        '- Complex calculations that would be error-prone by hand\n'
        '- Numerical verification of analytical results\n'
        '- Generating examples or testing conjectures\n'
        '- Visualizing problem structure when helpful\n'
        '- Brute-force verification for small cases\n\n'
        
        'The environment is a stateful Jupyter notebook. Code persists between executions.\n'
        'Always use print() to display results. Write clear, well-commented code.\n\n'
        
        'Remember: Code should support your mathematical reasoning, not replace it. '
        'Explain what you\'re computing and why before running code.'
    )
    
    preference_prompt = (
        'You have access to `math`, `numpy`, and `sympy` for:\n\n'
        
        '# Symbolic Computation (sympy):\n'
        '- Algebraic manipulation and simplification\n'
        '- Solving equations and systems of equations\n'
        '- Symbolic differentiation and integration\n'
        '- Number theory functions (primes, divisors, modular arithmetic)\n'
        '- Polynomial operations and factorization\n'
        '- Working with mathematical expressions symbolically\n\n'
        
        '# Numerical Computation (numpy):\n'
        '- Array operations and linear algebra\n'
        '- Efficient numerical calculations for large datasets\n'
        '- Matrix operations and eigenvalue problems\n'
        '- Statistical computations\n\n'
        
        '# Mathematical Functions (math):\n'
        '- Standard mathematical functions (trig, log, exp)\n'
        '- Constants like pi and e\n'
        '- Basic operations for single values\n\n'
        
        'Best Practices:\n'
        '- Use sympy for exact symbolic answers when possible\n'
        '- Use numpy for numerical verification and large-scale computation\n'
        '- Combine symbolic and numerical approaches: derive symbolically, verify numerically\n'
        '- Document your computational strategy clearly\n'
        '- Validate computational results against known cases or theoretical bounds\n'
        '- IMPORTANT: Write Python brute-force or search loops to guarantee exact integer answers when analytical methods stall'
    )    
    served_model_name = 'gpt-oss'
    model_path = '/kaggle/input/models/danielhanchen/gpt-oss-120b/transformers/default/1'
    
    kv_cache_dtype = 'fp8_e4m3'
    dtype = 'auto'

    high_problem_timeout = 900
    base_problem_timeout = 300

    notebook_limit = 17400
    server_timeout = 180

    session_timeout = 960
    jupyter_timeout = 6
    sandbox_timeout = 3

    stream_interval = 200
    context_tokens = 65536
    buffer_tokens = 512
    search_tokens = 32
    top_logprobs = 5
    batch_size = 256
    early_stop = 6
    attempts = 16
    workers = 16
    turns = 128
    seed = 42

    gpu_memory_utilization = 0.96
    temperature = 1.0
    min_p = 0.02

In [15]:
set_seed(ARCConfig.seed)

In [16]:
class ARCTemplate:

    def __init__(self):

        pass

    def get_system_content(self, system_prompt: str, tool_config: ToolNamespaceConfig) -> SystemContent:

        return (
            SystemContent.new()
            .with_model_identity(system_prompt)
            .with_reasoning_effort(reasoning_effort=ReasoningEffort.HIGH)
            .with_tools(tool_config)
        )

    def apply_chat_template(
        self, 
        system_prompt: str, 
        user_prompt: str, 
        tool_config: ToolNamespaceConfig
    ) -> list[Message]:

        system_content = self.get_system_content(system_prompt, tool_config)        
        system_message = Message.from_role_and_content(Role.SYSTEM, system_content)

        user_message = Message.from_role_and_content(Role.USER, user_prompt)

        return [system_message, user_message]

In [17]:
class ARCSandbox:

    _port_lock = threading.Lock()
    _next_port = 50000

    @classmethod
    def _get_next_ports(cls, count: int = 5) -> list[int]:

        with cls._port_lock:
            ports = list(range(cls._next_port, cls._next_port + count))
            cls._next_port += count

            return ports

    def __init__(self, timeout: float):

        self._default_timeout = timeout
        self._owns_kernel = False
        self._client = None
        self._km = None
        
        ports = self._get_next_ports(5)

        env = os.environ.copy()
        env['PYDEVD_DISABLE_FILE_VALIDATION'] = '1'
        env['PYDEVD_WARN_EVALUATION_TIMEOUT'] = '0'
        env['JUPYTER_PLATFORM_DIRS'] = '1'
        env['PYTHONWARNINGS'] = 'ignore'
        env['MPLBACKEND'] = 'Agg'

        self._km = KernelManager()
        self._km.shell_port = ports[0]
        self._km.iopub_port = ports[1]
        self._km.stdin_port = ports[2]
        self._km.hb_port = ports[3]
        self._km.control_port = ports[4]

        self._km.start_kernel(env=env, extra_arguments=['--Application.log_level=CRITICAL'])

        self._client = self._km.blocking_client()
        self._client.start_channels()
        self._client.wait_for_ready(timeout=self._default_timeout)
        self._owns_kernel = True

        self.execute(
            'import math\n'
            'import numpy\n'
            'import sympy\n'
            'import itertools\n'
            'import collections\n'
            'import mpmath\n'
            'mpmath.mp.dps = 64\n'
        )

    def _format_error(self, traceback: list[str]) -> str:

        clean_lines = []

        for frame in traceback:
            clean_frame = re.sub(r'\x1b\[[0-9;]*m', '', frame)

            if 'File "' in clean_frame and 'ipython-input' not in clean_frame:
                continue

            clean_lines.append(clean_frame)

        return ''.join(clean_lines)

    def execute(self, code: str, timeout: float | None = None) -> str:

        client = self._client
        effective_timeout = timeout or self._default_timeout
        
        msg_id = client.execute(
            code, 
            store_history=True, 
            allow_stdin=False, 
            stop_on_error=False
        )

        stdout_parts = []
        stderr_parts = []
        
        start_time = time.time()

        while True:
            elapsed = time.time() - start_time

            if elapsed > effective_timeout:
                self._km.interrupt_kernel()

                return f'[ERROR] Execution timed out after {effective_timeout} seconds'

            try:
                msg = client.get_iopub_msg(timeout=1.0)

            except queue.Empty:
                continue

            if msg.get('parent_header', {}).get('msg_id') != msg_id:
                continue

            msg_type = msg.get('msg_type')
            content = msg.get('content', {})

            if msg_type == 'stream':
                text = content.get('text', '')

                if content.get('name') == 'stdout':
                    stdout_parts.append(text)

                else:
                    stderr_parts.append(text)

            elif msg_type == 'error':
                traceback_list = content.get('traceback', [])

                stderr_parts.append(self._format_error(traceback_list))

            elif msg_type in {'execute_result', 'display_data'}:
                data = content.get('data', {})
                text = data.get('text/plain')

                if text:
                    stdout_parts.append(text if text.endswith('\n') else f'{text}\n')

            elif msg_type == 'status':
                if content.get('execution_state') == 'idle':
                    break

        stdout = ''.join(stdout_parts)
        stderr = ''.join(stderr_parts)

        if stderr:
            return f'{stdout.rstrip()}\n{stderr}' if stdout else stderr

        return stdout if stdout.strip() else '[WARN] No output. Use print() to see results.'

    def close(self):

        with contextlib.suppress(Exception):
            if self._client:
                self._client.stop_channels()

        if self._owns_kernel and self._km is not None:
            with contextlib.suppress(Exception):
                self._km.shutdown_kernel(now=True)

            with contextlib.suppress(Exception):
                self._km.cleanup_resources()

    def reset(self):
        
        self.execute(
            '%reset -f\n'
            'import math\n'
            'import numpy\n'
            'import sympy\n'
            'import itertools\n'
            'import collections\n'
            'import mpmath\n'
            'mpmath.mp.dps = 64\n'
        )

    def __del__(self):

        self.close()

In [18]:
class ARCTool:

    def __init__(self, local_jupyter_timeout: float, tool_prompt: str, sandbox=None):

        self._local_jupyter_timeout = local_jupyter_timeout
        self._tool_prompt = tool_prompt
        self._jupyter_session = sandbox
        
        self._owns_session = sandbox is None
        
        self._execution_lock = threading.Lock()
        self._init_lock = threading.Lock()

    def _ensure_session(self):

        if self._jupyter_session is None:
            with self._init_lock:
                if self._jupyter_session is None:
                    self._jupyter_session = ARCSandbox(timeout=self._local_jupyter_timeout)

    def _ensure_last_print(self, code: str) -> str:

        lines = code.strip().split('\n')

        if not lines:
            return code

        last_line = lines[-1].strip()

        if 'print' in last_line or 'import' in last_line:
            return code

        if not last_line:
            return code

        if last_line.startswith('#'):
            return code

        lines[-1] = 'print(' + last_line + ')'

        return '\n'.join(lines)

    @property
    def instruction(self) -> str:

        return self._tool_prompt

    @property
    def tool_config(self) -> ToolNamespaceConfig:

        return ToolNamespaceConfig(
            name='python', 
            description=self.instruction, 
            tools=[]
        )

    def _make_response(self, output: str, channel: str | None = None) -> Message:

        content = TextContent(text=output)
        author = Author(role=Role.TOOL, name='python')
        message = Message(author=author, content=[content]).with_recipient('assistant')

        if channel:
            message = message.with_channel(channel)

        return message

    def process_sync_plus(self, message: Message) -> list[Message]:

        self._ensure_session()
        raw_script = message.content[0].text
        final_script = self._ensure_last_print(raw_script)

        with self._execution_lock:
            try:
                output = self._jupyter_session.execute(final_script)

            except TimeoutError as exc:
                output = f'[ERROR] {exc}'

        return [self._make_response(output, channel=message.channel)]

In [19]:
class ARCSolver:

    def __init__(self, cfg, port: int = 8000):
    
        self.cfg = cfg
        self.port = port
        self.base_url = f'http://0.0.0.0:{port}/v1'
        self.api_key = 'sk-local'
        self.template = ARCTemplate()
        self.encoding = load_harmony_encoding(HarmonyEncodingName.HARMONY_GPT_OSS)
        self.stop_token_ids = self.encoding.stop_tokens_for_assistant_actions()
    
        self._preload_model_weights()
        
        self.server_process = self._start_server()
    
        self.client = OpenAI(
            base_url=self.base_url, 
            api_key=self.api_key, 
            timeout=self.cfg.session_timeout
        )
    
        self._wait_for_server()
        self._initialize_kernels()
    
        self.notebook_start_time = time.time()
        self.problems_remaining = 50
    
    def _preload_model_weights(self) -> None:
    
        print(f'Loading model weights from {self.cfg.model_path} into OS Page Cache...')
        start_time = time.time()
        
        files_to_load = []
        total_size = 0
    
        for root, _, files in os.walk(self.cfg.model_path):
            for file_name in files:
                file_path = os.path.join(root, file_name)
    
                if os.path.isfile(file_path):
                    files_to_load.append(file_path)
                    total_size += os.path.getsize(file_path)
    
        def _read_file(path: str) -> None:
    
            with open(path, 'rb') as file_object:
                while file_object.read(1024 * 1024 * 1024):
                    pass
    
        with ThreadPoolExecutor(max_workers=self.cfg.workers) as executor:
            list(executor.map(_read_file, files_to_load))
    
        elapsed = time.time() - start_time
        print(f'Processed {len(files_to_load)} files ({total_size / 1e9:.2f} GB) in {elapsed:.2f} seconds.\n')
    
    def _start_server(self) -> subprocess.Popen:
    
        cmd = [
            sys.executable, 
            '-m', 
            'vllm.entrypoints.openai.api_server', 
            '--seed', 
            str(self.cfg.seed), 
            '--model', 
            self.cfg.model_path, 
            '--served-model-name', 
            self.cfg.served_model_name, 
            '--tensor-parallel-size', 
            '1', 
            '--max-num-seqs', 
            str(self.cfg.batch_size), 
            '--gpu-memory-utilization', 
            str(self.cfg.gpu_memory_utilization), 
            '--host', 
            '0.0.0.0', 
            '--port', 
            str(self.port), 
            '--dtype', 
            self.cfg.dtype, 
            '--kv-cache-dtype', 
            self.cfg.kv_cache_dtype, 
            '--max-model-len', 
            str(self.cfg.context_tokens), 
            '--stream-interval', 
            str(self.cfg.stream_interval), 
            '--async-scheduling', 
            '--disable-log-stats', 
            '--enable-prefix-caching'
        ]
    
        self.log_file = open('vllm_server.log', 'w')
    
        return subprocess.Popen(
            cmd, 
            stdout=self.log_file, 
            stderr=subprocess.STDOUT, 
            start_new_session=True
        )
    
    def _wait_for_server(self):
    
        print('Waiting for vLLM server...')
        start_time = time.time()
    
        for _ in range(self.cfg.server_timeout):
            return_code = self.server_process.poll()
    
            if return_code is not None:
                self.log_file.flush()
    
                with open('vllm_server.log', 'r') as log_file:
                    logs = log_file.read()
    
                raise RuntimeError(f'Server died with code {return_code}. Full logs:\n{logs}\n')
    
            try:
                self.client.models.list()
                elapsed = time.time() - start_time
                print(f'Server is ready (took {elapsed:.2f} seconds).\n')
    
                return
    
            except Exception:
                time.sleep(1)
    
        raise RuntimeError('Server failed to start (timeout).\n')
    
    def _initialize_kernels(self) -> None:
    
        print(f'Initializing {self.cfg.workers} persistent Jupyter kernels...')
        start_time = time.time()
    
        self.sandbox_pool = queue.Queue()
    
        def _create_sandbox():
            
            return ARCSandbox(timeout=self.cfg.jupyter_timeout)
    
        with ThreadPoolExecutor(max_workers=self.cfg.workers) as executor:
            futures = [executor.submit(_create_sandbox) for _ in range(self.cfg.workers)]
    
            for future in as_completed(futures):
                self.sandbox_pool.put(future.result())
    
        elapsed = time.time() - start_time
        print(f'Kernels initialized in {elapsed:.2f} seconds.\n')
    
    def _scan_for_answer(self, text: str) -> int | None:
        
        pattern = r'\\boxed\s*\{\s*([0-9,]+)\s*\}'
        matches = re.findall(pattern, text)
    
        if matches:
            try:
                clean_value = matches[-1].replace(',', '')
                value = int(clean_value)
    
                if 0 <= value <= 99999:
                    return value
    
            except ValueError:
                pass
                
        pattern = r'final\s+answer\s+is\s*([0-9,]+)'
        matches = re.findall(pattern, text, re.IGNORECASE)
    
        if matches:
            try:
                clean_value = matches[-1].replace(',', '')
                value = int(clean_value)
    
                if 0 <= value <= 99999:
                    return value
    
            except ValueError:
                pass
    
        return None
    
    def _compute_mean_entropy(self, logprobs_buffer: list) -> float:
    
        if not logprobs_buffer:
            return float('inf')
    
        total_entropy = 0.0
        token_count = 0
    
        for top_logprobs_dict in logprobs_buffer:
            
            if not isinstance(top_logprobs_dict, dict):
                continue
            
            if not top_logprobs_dict:
                continue
            
            token_entropy = 0.0
            
            for token_str, log_prob in top_logprobs_dict.items():
                prob = math.exp(log_prob)
                
                if prob > 0:
                    token_entropy -= prob * math.log2(prob)
            
            total_entropy += token_entropy
            token_count += 1
    
        if token_count == 0:
            return float('inf')
    
        return total_entropy / token_count
    
    def _process_attempt(
        self, 
        problem: str, 
        system_prompt: str, 
        attempt_index: int, 
        stop_event: threading.Event, 
        deadline: float
    ) -> dict:
    
        if stop_event.is_set() or time.time() > deadline:
            return {
                'Attempt': attempt_index + 1, 
                'Answer': None, 
                'Python Calls': 0, 
                'Python Errors': 0, 
                'Response Length': 0, 
                'Entropy': float('inf')
            }
    
        local_tool = None
        sandbox = None
        python_calls = 0
        python_errors = 0
        total_tokens = 0
        final_answer = None
        
        logprobs_buffer = []
    
        attempt_seed = int(math.pow(self.cfg.seed + attempt_index, 2))
    
        try:
            sandbox = self.sandbox_pool.get(timeout=self.cfg.sandbox_timeout)
    
            local_tool = ARCTool(
                local_jupyter_timeout=self.cfg.jupyter_timeout, 
                tool_prompt=self.cfg.tool_prompt, 
                sandbox=sandbox
            )
    
            encoding = self.encoding
            messages = self.template.apply_chat_template(
                system_prompt, 
                problem, 
                local_tool.tool_config
            )
    
            conversation = Conversation.from_messages(messages)
    
            for _ in range(self.cfg.turns):
                if stop_event.is_set() or time.time() > deadline:
                    break
    
                prompt_ids = encoding.render_conversation_for_completion(conversation, Role.ASSISTANT)
                max_tokens = self.cfg.context_tokens - len(prompt_ids)
    
                if max_tokens < self.cfg.buffer_tokens:
                    break
    
                stream = self.client.completions.create(
                    model=self.cfg.served_model_name, 
                    temperature=self.cfg.temperature, 
                    logprobs=self.cfg.top_logprobs, 
                    max_tokens=max_tokens, 
                    prompt=prompt_ids, 
                    seed=attempt_seed, 
                    stream=True, 
                    extra_body={
                        'min_p': self.cfg.min_p, 
                        'stop_token_ids': self.stop_token_ids, 
                        'return_token_ids': True
                    }
                )
    
                try:
                    token_buffer = []
                    text_chunks = []
    
                    for chunk in stream:
                        if stop_event.is_set() or time.time() > deadline:
                            break
    
                        new_tokens = chunk.choices[0].token_ids
                        new_text = chunk.choices[0].text
    
                        if new_tokens:
                            token_buffer.extend(new_tokens)
                            total_tokens += len(new_tokens)
                            text_chunks.append(new_text)
                            
                            chunk_logprobs = chunk.choices[0].logprobs
                            
                            if chunk_logprobs is not None:
                                if chunk_logprobs.top_logprobs:
                                    logprobs_buffer.extend(chunk_logprobs.top_logprobs)
    
                        if '}' in new_text:
                            search_text = ''.join(text_chunks[-self.cfg.search_tokens:])
                            answer = self._scan_for_answer(search_text)
    
                            if answer is not None:
                                final_answer = answer
                                break
    
                finally:
                    stream.close()
    
                if final_answer is not None:
                    break
    
                if not token_buffer:
                    break
    
                new_messages = encoding.parse_messages_from_completion_tokens(token_buffer, Role.ASSISTANT)
                conversation.messages.extend(new_messages)
                last_message = new_messages[-1]
    
                if last_message.channel == 'final':
                    answer_text = last_message.content[0].text
                    final_answer = self._scan_for_answer(answer_text)
                    break
    
                if last_message.recipient == 'python':
                    python_calls += 1
                    tool_responses = local_tool.process_sync_plus(last_message)
    
                    response_text = tool_responses[0].content[0].text
    
                    if response_text.startswith('[ERROR]') or 'Traceback' in response_text or 'Error:' in response_text:
                        python_errors += 1
    
                    conversation.messages.extend(tool_responses)
    
        except Exception as exc:
            python_errors += 1
    
        finally:
            if sandbox is not None:
                sandbox.reset()
                self.sandbox_pool.put(sandbox)
    
        mean_entropy = self._compute_mean_entropy(logprobs_buffer)
    
        return {
            'Attempt': attempt_index + 1, 
            'Response Length': total_tokens, 
            'Python Calls': python_calls, 
            'Python Errors': python_errors, 
            'Entropy': mean_entropy, 
            'Answer': final_answer
        }
    
    def _select_answer(self, detailed_results: list) -> int:

        answer_weights = defaultdict(float)
        answer_votes = defaultdict(int)

        for result in detailed_results:
            answer = result['Answer']
            entropy = result['Entropy']
            
            if answer is not None:
                weight = 1.0 / max(entropy, 1e-9)
                
                answer_weights[answer] += weight
                answer_votes[answer] += 1

        scored_answers = []

        for answer, total_weight in answer_weights.items():
            scored_answers.append({
                'answer': answer, 
                'votes': answer_votes[answer], 
                'score': total_weight
            })

        scored_answers.sort(key=lambda x: x['score'], reverse=True)

        vote_data = []

        for item in scored_answers:
            vote_data.append((
                item['answer'], 
                item['votes'], 
                item['score']
            ))

        vote_dataframe = pd.DataFrame(
            vote_data, 
            columns=['Answer', 'Votes', 'Score']
        )

        vote_dataframe = vote_dataframe.round({'Score': 3})
        display(vote_dataframe)
        
        if not scored_answers:
            print('\nFinal Answer: 0\n')
            return 0

        final_answer = scored_answers[0]['answer']    
        print(f'\nFinal Answer: {final_answer}\n')

        return final_answer
    
    def solve_problem(self, problem: str) -> int:
    
        print(f'\nProblem: {problem}\n')
        
        user_input = f'{problem} {self.cfg.preference_prompt}'
    
        elapsed_global = time.time() - self.notebook_start_time
        time_left = self.cfg.notebook_limit - elapsed_global
        problems_left_others = max(0, self.problems_remaining - 1)
        reserved_time = problems_left_others * self.cfg.base_problem_timeout
    
        budget = time_left - reserved_time
        budget = min(budget, self.cfg.high_problem_timeout)
        budget = max(budget, self.cfg.base_problem_timeout)
    
        deadline = time.time() + budget
    
        print(f'Budget: {budget:.2f} seconds | Deadline: {deadline:.2f}\n')
    
        tasks = []
    
        for attempt_index in range(self.cfg.attempts):
            tasks.append((self.cfg.system_prompt, attempt_index))
    
        detailed_results = []
        valid_answers = []
    
        stop_event = threading.Event()
    
        executor = ThreadPoolExecutor(max_workers=self.cfg.workers)
    
        try:
            futures = []
    
            for (system_prompt, attempt_index) in tasks:
                future = executor.submit(
                    self._process_attempt, 
                    user_input, 
                    system_prompt, 
                    attempt_index, 
                    stop_event, 
                    deadline
                )
    
                futures.append(future)
    
            for future in as_completed(futures):
                try:
                    result = future.result()
                    detailed_results.append(result)
    
                    if result['Answer'] is not None:
                        valid_answers.append(result['Answer'])
    
                    counts = Counter(valid_answers).most_common(1)
    
                    if counts and counts[0][1] >= self.cfg.early_stop:
                        stop_event.set()
    
                        for f in futures:
                            f.cancel()
    
                        break
    
                except Exception as exc:
                    print(f'Future failed: {exc}')
                    continue
    
        finally:
            stop_event.set()
            executor.shutdown(wait=True, cancel_futures=True)
            
            self.problems_remaining = max(0, self.problems_remaining - 1)
    
        if detailed_results:
            results_dataframe = pd.DataFrame(detailed_results)
            results_dataframe['Entropy'] = results_dataframe['Entropy'].round(3)
            results_dataframe['Answer'] = results_dataframe['Answer'].astype('Int64')
            
            display(results_dataframe)
    
        if not valid_answers:
            print('\nResult: 0\n')
    
            return 0
    
        return self._select_answer(detailed_results)
    
    def __del__(self):
    
        if hasattr(self, 'server_process'):
            self.server_process.terminate()
            self.server_process.wait()
    
        if hasattr(self, 'log_file'):
            self.log_file.close()
    
        if hasattr(self, 'sandbox_pool'):
            while not self.sandbox_pool.empty():
                try:
                    sb = self.sandbox_pool.get_nowait()
                    sb.close()
    
                except Exception:
                    pass

In [20]:
solver = ARCSolver(ARCConfig)

Loading model weights from /kaggle/input/models/danielhanchen/gpt-oss-120b/transformers/default/1 into OS Page Cache...
Processed 26 files (65.28 GB) in 64.84 seconds.

Waiting for vLLM server...
Server is ready (took 127.41 seconds).

Initializing 16 persistent Jupyter kernels...
Kernels initialized in 2.95 seconds.

In [21]:
import polars as pl
import pandas as pd
import os

# --- 1. Updated Predict Function ---
def predict(id_: pl.DataFrame, question: pl.DataFrame, answer: Optional[pl.DataFrame] = None) -> pl.DataFrame:
    # Use index-based access to avoid the .item() error
    id_value = id_[0, 0]
    question_text = question[0, 0]
    
    gc.disable()
    final_answer = solver.solve_problem(question_text)
    gc.enable()
    gc.collect()
    
    return pl.DataFrame({'id': id_value, 'answer': final_answer})

# --- 2. Updated Testing Loop ---
FILE_PATH = '/kaggle/input/datasets/amanatar/50problems/50problems.csv'

if not os.path.exists(FILE_PATH):
    print(f"Error: File not found at {FILE_PATH}")
else:
    external_df = pd.read_csv(FILE_PATH)
    test_results = []

    print(f"Starting test on {len(external_df)} problems...\n")

    for idx, row in external_df.iterrows():
        problem_text = row['Problem']
        ground_truth = row['Answer']
        
        # Step 1: Print problem details first
        print(f"{'='*50}")
        print(f"TESTING PROBLEM {idx+1}")
        print(f"Statement: {problem_text}")
        print(f"Ground Truth Answer: {ground_truth}")
        print(f"{'-'*50}")
        
        # Prepare inputs
        id_df = pl.DataFrame({'id': [f"ext_{idx}"]})
        question_df = pl.DataFrame({'question': [problem_text]})
        
        try:
            # Step 2: Generate Answer
            result_pl_df = predict(id_df, question_df)
            
            # Accessing column 'answer' from row 0
            predicted_val = result_pl_df[0, "answer"]
            
            is_correct = (int(predicted_val) == int(ground_truth))
            
            test_results.append({
                "idx": idx + 1,
                "prediction": predicted_val,
                "ground_truth": ground_truth,
                "correct": is_correct
            })
            
            # Step 3: Print result summary before moving to next
            status = "✅ CORRECT" if is_correct else "❌ INCORRECT"
            print(f"\n[Problem {idx+1} Result]")
            print(f"Model Predicted: {predicted_val}")
            print(f"Status: {status}")
            print(f"{'='*50}\n")
            
        except Exception as e:
            print(f"Error on problem {idx+1}: {e}")
            test_results.append({
                "idx": idx + 1, "prediction": None, "ground_truth": ground_truth, "correct": False
            })

    # Final Summary Table
    summary_df = pd.DataFrame(test_results)
    display(summary_df)
    print(f"Overall Accuracy: {summary_df['correct'].mean() * 100:.2f}%")

Starting test on 50 problems...

==================================================
TESTING PROBLEM 1
Statement: Let $ABC$ be an acute-angled triangle with integer side lengths and $AB<AC$. Points $D$ and $E$ lie on segments $BC$ and $AC$, respectively, such that $AD=AE=AB$. Line $DE$ intersects $AB$ at $X$. Circles $BXD$ and $CED$ intersect for the second time at $Y \neq D$. Suppose that $Y$ lies on line $AD$. There is a unique such triangle with minimal perimeter. This triangle has side lengths $a=BC$, $b=CA$, and $c=AB$. Find the remainder when $abc$ is divided by $10^{5}$.
Ground Truth Answer: 336
--------------------------------------------------

Problem: Let $ABC$ be an acute-angled triangle with integer side lengths and $AB<AC$. Points $D$ and $E$ lie on segments $BC$ and $AC$, respectively, such that $AD=AE=AB$. Line $DE$ intersects $AB$ at $X$. Circles $BXD$ and $CED$ intersect for the second time at $Y \neq D$. Suppose that $Y$ lies on line $AD$. There is a unique such triangle with minimal perimeter. This triangle has side lengths $a=BC$, $b=CA$, and $c=AB$. Find the remainder when $abc$ is divided by $10^{5}$.

Budget: 900.00 seconds | Deadline: 1775759153.75

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6            11389            10              3    0.556     336
1        2            14949            19              0    0.541     336
2        1            15323             9              1    0.617     336
3        7            15862            15              1    0.613     336

   Answer  Votes  Score
0     336      4  6.899

Final Answer: 336


[Problem 1 Result]
Model Predicted: 336
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 2
Statement: Define a function $f \colon \mathbb{Z}_{\geq 1} \to \mathbb{Z}_{\geq 1}$ by $f(n) = \sum_{i = 1}^n \sum_{j = 1}^n j^{1024} \lfloor\frac1j + \frac{n-i}{n}\rfloor$. Let $M=2 \cdot 3 \cdot 5 \cdot 7 \cdot 11 \cdot 13$ and let $N = f(M^{15}) - f(M^{15}-1)$. Let $k$ be the largest non-negative integer such that $2^k$ divides $N$. What is the remainder when $2^k$ is divided by $5^7$?
Ground Truth Answer: 32951
--------------------------------------------------

Problem: Define a function $f \colon \mathbb{Z}_{\geq 1} \to \mathbb{Z}_{\geq 1}$ by $f(n) = \sum_{i = 1}^n \sum_{j = 1}^n j^{1024} \lfloor\frac1j + \frac{n-i}{n}\rfloor$. Let $M=2 \cdot 3 \cdot 5 \cdot 7 \cdot 11 \cdot 13$ and let $N = f(M^{15}) - f(M^{15}-1)$. Let $k$ be the largest non-negative integer such that $2^k$ divides $N$. What is the remainder when $2^k$ is divided by $5^7$?

Budget: 900.00 seconds | Deadline: 1775759340.02

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        8             4515             5              0    0.565   32951
1        7             4771             5              0    0.625   32951
2        4             4939             1              0    0.599   32951
3        5             6470             6              0    0.570   32951

   Answer  Votes  Score
0   32951      4  6.795

Final Answer: 32951


[Problem 2 Result]
Model Predicted: 32951
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 3
Statement: A tournament is held with $2^{20}$ runners each of which has a different running speed. The competition consists of $20$ rounds. The winner of each race in the $i^{\text{th}}$ round receives $2^{20-i}$ points and the loser gets no points. Let $N$ denote the number of possible orderings of the competitors at the end of the tournament. Let $k$ be the largest positive integer such that $10^k$ divides $N$. What is the remainder when $k$ is divided by $10^{5}$?
Ground Truth Answer: 21818
--------------------------------------------------

Problem: A tournament is held with $2^{20}$ runners each of which has a different running speed. The competition consists of $20$ rounds. The winner of each race in the $i^{\text{th}}$ round receives $2^{20-i}$ points and the loser gets no points. Let $N$ denote the number of possible orderings of the competitors at the end of the tournament. Let $k$ be the largest positive integer such that $10^k$ divides $N$. What is the remainder when $k$ is divided by $10^{5}$?

Budget: 900.00 seconds | Deadline: 1775759399.38

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7             7082             6              1    0.949   62097
1        2            15730             8              0    0.893   24237
2        1            20033             3              0    0.997   62097
3        4            23346            12              0    0.857   24237
4        6            52480            29              5    0.829      20
5        3            62915            42              2    0.786    <NA>
6        8            63133            18              2    0.851    <NA>
7        5            64330            14              4    0.886    <NA>

   Answer  Votes  Score
0   24237      2  2.286
1   62097      2  2.057
2      20      1  1.206

Final Answer: 24237


[Problem 3 Result]
Model Predicted: 24237
Status: ❌ INCORRECT
==================================================

==================================================
TESTING PROBLEM 4
Statement: Ken writes a positive integer $n$ on a blackboard. If the number is $m$, he chooses a base $b$, $2 \leq b \leq m$, and replaces $m$ with the sum of its digits in base $b$. Across all $1 \leq n \leq 10^{10^5}$, the largest possible number of moves Ken could make is $M$. What is the remainder when $M$ is divided by $10^{5}$?
Ground Truth Answer: 32193
--------------------------------------------------

Problem: Ken writes a positive integer $n$ on a blackboard. If the number is $m$, he chooses a base $b$, $2 \leq b \leq m$, and replaces $m$ with the sum of its digits in base $b$. Across all $1 \leq n \leq 10^{10^5}$, the largest possible number of moves Ken could make is $M$. What is the remainder when $M$ is divided by $10^{5}$?

Budget: 900.00 seconds | Deadline: 1775760005.47

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        5             4550             7              0    0.707   32193
1        8             6063             7              1    0.735   32193
2        2             6226            11              0    0.706   32193
3        1             6652            12              0    0.763   32193

   Answer  Votes  Score
0   32193      4  5.501

Final Answer: 32193


[Problem 4 Result]
Model Predicted: 32193
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 5
Statement: Let triangle $ABC$ be $n$-tastic if $BD = F_n, CD = F_{n+1},$ and $KNK'B$ is cyclic, where $K$ is a meeting point of circumcircles and $N$ is the foot of the perpendicular from $D$ to $EF$. Across all $n$-tastic triangles, let $a_n$ be the max value of $\frac{CT \cdot NB}{BT \cdot NE}$. Let $\alpha = p + \sqrt{q}$ be the limit as $n \to \infty$. Find the remainder when $\lfloor p^{q^p} \rfloor$ is divided by $99991$.
Ground Truth Answer: 57447
--------------------------------------------------

Problem: Let triangle $ABC$ be $n$-tastic if $BD = F_n, CD = F_{n+1},$ and $KNK'B$ is cyclic, where $K$ is a meeting point of circumcircles and $N$ is the foot of the perpendicular from $D$ to $EF$. Across all $n$-tastic triangles, let $a_n$ be the max value of $\frac{CT \cdot NB}{BT \cdot NE}$. Let $\alpha = p + \sqrt{q}$ be the limit as $n \to \infty$. Find the remainder when $\lfloor p^{q^p} \rfloor$ is divided by $99991$.

Budget: 900.00 seconds | Deadline: 1775760071.91

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        5             1719             2              0    0.783   57447
1        8             2469             2              0    0.793   57447
2        3             8266             6              0    0.774   57447
3        7            16829            16              2    0.635   57447

   Answer  Votes  Score
0   57447      4  5.406

Final Answer: 57447


[Problem 5 Result]
Model Predicted: 57447
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 6
Statement: A positive integer is $n$-Norwegian if it has three distinct positive divisors whose sum is $n$. Let $f(n)$ denote the smallest $n$-Norwegian integer. Let $M=3^{2025!}$ and $g(c)=\frac{1}{2025!}\lfloor \frac{2025! f(M+c)}{M}\rfloor$. If $g(0)+g(4M)+g(1848374)+g(10162574)+g(265710644)+g(44636594)=\frac{p}{q}$, find the remainder when $p+q$ is divided by $99991$.
Ground Truth Answer: 8687
--------------------------------------------------

Problem: A positive integer is $n$-Norwegian if it has three distinct positive divisors whose sum is $n$. Let $f(n)$ denote the smallest $n$-Norwegian integer. Let $M=3^{2025!}$ and $g(c)=\frac{1}{2025!}\lfloor \frac{2025! f(M+c)}{M}\rfloor$. If $g(0)+g(4M)+g(1848374)+g(10162574)+g(265710644)+g(44636594)=\frac{p}{q}$, find the remainder when $p+q$ is divided by $99991$.

Budget: 900.00 seconds | Deadline: 1775760238.26

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7            36543            51              8    0.707   41754
1        4            40651            33              2    0.699     106
2        2            38716            74              7    0.694    8687
3        8            40132            56             10    0.688    <NA>
4        6            46218            38              7    0.660    <NA>
5        3            50608            34              3    0.682    8687
6        5            56887            44              6    0.672    <NA>
7        1            64673             0              0    0.550    <NA>

   Answer  Votes  Score
0    8687      2  2.906
1     106      1  1.431
2   41754      1  1.415

Final Answer: 8687


[Problem 6 Result]
Model Predicted: 8687
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 7
Statement: Alice and Bob each hold some sweets. Alice says: If we added our sweets to our positive integer age, my answer would be double yours. If we took the product, my answer would be four times yours. Bob says: Give me five sweets and then both our sum and product would be equal. What is the product of Alice and Bob's ages?
Ground Truth Answer: 50
--------------------------------------------------

Problem: Alice and Bob each hold some sweets. Alice says: If we added our sweets to our positive integer age, my answer would be double yours. If we took the product, my answer would be four times yours. Bob says: Give me five sweets and then both our sum and product would be equal. What is the product of Alice and Bob's ages?

Budget: 900.00 seconds | Deadline: 1775760889.50

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        4             2548             1              0    0.669      50
1        3             2662             2              0    0.646      50
2        1             3628             5              1    0.578      50
3        2             3609             2              1    0.578      50

   Answer  Votes  Score
0      50      4  6.505

Final Answer: 50


[Problem 7 Result]
Model Predicted: 50
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 8
Statement: Let $f \colon \mathbb{Z}_{\geq 1} \to \mathbb{Z}_{\geq 1}$ satisfy $f(m) + f(n) = f(m + n + mn)$ for all $m, n$. Across all functions where $f(n) \leq 1000$ for all $n \leq 1000$, how many different values can $f(2024)$ take?
Ground Truth Answer: 580
--------------------------------------------------

Problem: Let $f \colon \mathbb{Z}_{\geq 1} \to \mathbb{Z}_{\geq 1}$ satisfy $f(m) + f(n) = f(m + n + mn)$ for all $m, n$. Across all functions where $f(n) \leq 1000$ for all $n \leq 1000$, how many different values can $f(2024)$ take?

Budget: 900.00 seconds | Deadline: 1775760934.17

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7             9180             5              0    0.710     580
1        8             8913             4              1    0.736     580
2        5             9584             5              2    0.745     580
3        6             9588             6              1    0.762     580

   Answer  Votes  Score
0     580      4  5.421

Final Answer: 580


[Problem 8 Result]
Model Predicted: 580
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 9
Statement: A $500 \times 500$ square is divided into $k$ rectangles with integer side lengths. Given that no two of these rectangles have the same perimeter, the largest possible value of $k$ is $\mathcal{K}$. What is the remainder when $\mathcal{K}$ is divided by $10^{5}$?
Ground Truth Answer: 520
--------------------------------------------------

Problem: A $500 \times 500$ square is divided into $k$ rectangles with integer side lengths. Given that no two of these rectangles have the same perimeter, the largest possible value of $k$ is $\mathcal{K}$. What is the remainder when $\mathcal{K}$ is divided by $10^{5}$?

Budget: 900.00 seconds | Deadline: 1775761036.33

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7            11093             1              0    0.923     520
1        6            15568             7              0    0.918     520
2        2            19716             8              0    0.945     520
3        1            23120             9              0    0.986     520

   Answer  Votes  Score
0     520      4  4.246

Final Answer: 520


[Problem 9 Result]
Model Predicted: 520
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 10
Statement: Let $\mathcal{F}$ be the set of functions $\alpha \colon \mathbb{Z} \to \mathbb{Z}$ with finite support. Define a product $\alpha \star \beta = \sum \alpha(n) \beta(n)$. A function is shifty if $\alpha(m)=0$ for $m<0, m>8$ and there exists $\beta$ such that $S_n(\alpha) \star \beta = 1$ for two distinct shifts and $0$ otherwise. How many shifty functions are there?
Ground Truth Answer: 160
--------------------------------------------------

Problem: Let $\mathcal{F}$ be the set of functions $\alpha \colon \mathbb{Z} \to \mathbb{Z}$ with finite support. Define a product $\alpha \star \beta = \sum \alpha(n) \beta(n)$. A function is shifty if $\alpha(m)=0$ for $m<0, m>8$ and there exists $\beta$ such that $S_n(\alpha) \star \beta = 1$ for two distinct shifts and $0$ otherwise. How many shifty functions are there?

Budget: 900.00 seconds | Deadline: 1775761259.58

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        1            10866             9              1    0.768     160
1        7            12169             8              2    0.780     266
2        3            12836            16              2    0.789      44
3        2            13567             8              0    0.864      45
4        4            16699            15              2    0.823      44
5        5            17466            22              2    0.768     160
6        6            24899            20              4    0.749     266
7        8            27914            35              5    0.729     160

   Answer  Votes  Score
0     160      3  3.976
1     266      2  2.618
2      44      2  2.483
3      45      1  1.158

Final Answer: 160


[Problem 10 Result]
Model Predicted: 160
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 11
Statement: Every morning Aya goes for a 9-km walk. At speed $s$ km/h, it takes 4 hours including $t$ minutes at a shop. At $s+2$ km/h, it takes 2 hours 24 minutes including $t$ minutes. If she walks at $s+0.5$ km/h, find the total number of minutes the walk takes including the coffee shop.
Ground Truth Answer: 204
--------------------------------------------------

Problem: Every morning Aya goes for a 9-km walk. At speed $s$ km/h, it takes 4 hours including $t$ minutes at a shop. At $s+2$ km/h, it takes 2 hours 24 minutes including $t$ minutes. If she walks at $s+0.5$ km/h, find the total number of minutes the walk takes including the coffee shop.

Budget: 900.00 seconds | Deadline: 1775761490.13

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        4              872             2              0    0.442     204
1        8              968             0              0    0.439     204
2        2             1001             0              0    0.472     204
3        6             1001             0              0    0.533     204

   Answer  Votes  Score
0     204      4  8.537

Final Answer: 204


[Problem 11 Result]
Model Predicted: 204
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 12
Statement: There exist real numbers $x, y > 1$ such that $x^{\log_x y} = \log_y (x^4 y) = 10$. Find $xy$.
Ground Truth Answer: 25
--------------------------------------------------

Problem: There exist real numbers $x, y > 1$ such that $x^{\log_x y} = \log_y (x^4 y) = 10$. Find $xy$.

Budget: 900.00 seconds | Deadline: 1775761500.67

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6             1255             1              0    0.576    <NA>
1        3             1508             2              0    0.526    <NA>
2        5             1573             1              0    0.551    <NA>
3        2             1867             1              0    0.639    <NA>
4        8             2474             2              0    0.814    <NA>
5        4             2701             3              0    0.763    1778
6        7             3223             2              0    0.849      42
7        1             4666             2              0    0.832    1778

   Answer  Votes  Score
0    1778      2  2.512
1      42      1  1.178

Final Answer: 1778


[Problem 12 Result]
Model Predicted: 1778
Status: ❌ INCORRECT
==================================================

==================================================
TESTING PROBLEM 13
Statement: Alice and Bob play a game with $n$ tokens. They take turns removing 1 or 4 tokens. The player who removes the last token wins. Find the number of positive integers $n \leq 2024$ for which Bob has a winning strategy regardless of Alice's moves.
Ground Truth Answer: 809
--------------------------------------------------

Problem: Alice and Bob play a game with $n$ tokens. They take turns removing 1 or 4 tokens. The player who removes the last token wins. Find the number of positive integers $n \leq 2024$ for which Bob has a winning strategy regardless of Alice's moves.

Budget: 900.00 seconds | Deadline: 1775761533.99

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        5             1698             4              0    0.630     809
1        3             1908             6              0    0.620     809
2        7             2030             5              0    0.658     809
3        8             2056             3              0    0.684     809

   Answer  Votes  Score
0     809      4  6.185

Final Answer: 809


[Problem 13 Result]
Model Predicted: 809
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 14
Statement: Jen picks 4 distinct numbers from $S=\{1,2,\dots,10\}$. 4 numbers are drawn randomly from $S$. She wins a prize if at least two match. The probability of winning the grand prize (all 4 match) given she wins a prize is $m/n$. Find $m+n$.
Ground Truth Answer: 116
--------------------------------------------------

Problem: Jen picks 4 distinct numbers from $S=\{1,2,\dots,10\}$. 4 numbers are drawn randomly from $S$. She wins a prize if at least two match. The probability of winning the grand prize (all 4 match) given she wins a prize is $m/n$. Find $m+n$.

Budget: 900.00 seconds | Deadline: 1775761555.23

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        5             1440             2              0    0.707     116
1        1             1532             3              0    0.707     116
2        7             1672             1              0    0.478     116
3        2             1982             1              0    0.488     116

   Answer  Votes  Score
0     116      4  6.971

Final Answer: 116


[Problem 14 Result]
Model Predicted: 116
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 15
Statement: Rectangle $ABCD$ has dimensions $107 \times 16$, and rectangle $EFGH$ has $184 \times 17$. $D, E, C, F$ lie on a line in that order. If $A, D, H, G$ lie on a common circle, find $CE$.
Ground Truth Answer: 104
--------------------------------------------------

Problem: Rectangle $ABCD$ has dimensions $107 \times 16$, and rectangle $EFGH$ has $184 \times 17$. $D, E, C, F$ lie on a line in that order. If $A, D, H, G$ lie on a common circle, find $CE$.

Budget: 900.00 seconds | Deadline: 1775761574.09

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        4             3846             6              0    0.670     104
1        7             4038             6              0    0.649     104
2        2             4538             1              0    0.695     104
3        5             5208            10              1    0.780     104

   Answer  Votes  Score
0     104      4  5.756

Final Answer: 104


[Problem 15 Result]
Model Predicted: 104
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 16
Statement: Consider paths of length 16 on an $8 \times 8$ grid from the lower-left to the upper-right corner. Find the number of such paths that change direction exactly four times.
Ground Truth Answer: 294
--------------------------------------------------

Problem: Consider paths of length 16 on an $8 \times 8$ grid from the lower-left to the upper-right corner. Find the number of such paths that change direction exactly four times.

Budget: 900.00 seconds | Deadline: 1775761623.73

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        8             1370             1              0    0.668     294
1        4             1447             1              0    0.766     294
2        3             1531             1              0    0.718     294
3        7             1960             1              0    0.835     294

   Answer  Votes  Score
0     294      4  5.393

Final Answer: 294


[Problem 16 Result]
Model Predicted: 294
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 17
Statement: Eight circles of radius 34 can be placed tangent to $BC$ of $\triangle ABC$ sequentially tangent to each other, first to $AB$ and last to $AC$. Similarly, 2024 circles of radius 1 can be placed the same way. Find $m+n$ if the inradius is $m/n$.
Ground Truth Answer: 540
--------------------------------------------------

Problem: Eight circles of radius 34 can be placed tangent to $BC$ of $\triangle ABC$ sequentially tangent to each other, first to $AB$ and last to $AC$. Similarly, 2024 circles of radius 1 can be placed the same way. Find $m+n$ if the inradius is $m/n$.

Budget: 900.00 seconds | Deadline: 1775761642.65

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        3             7988             7              0    0.755     197
1        5            11764             3              0    0.729     197
2        4            13843             8              0    0.658     197
3        2            15217             7              0    0.671     197

   Answer  Votes  Score
0     197      4  5.706

Final Answer: 197


[Problem 17 Result]
Model Predicted: 197
Status: ❌ INCORRECT
==================================================

==================================================
TESTING PROBLEM 18
Statement: Tetrahedron $ABCD$ has $AB=CD=\sqrt{41}$, $AC=BD=\sqrt{80}$, and $BC=AD=\sqrt{89}$. A point $I$ is equidistant from all faces. If this distance is $\frac{m\sqrt{n}}{p}$, find $m+n+p$.
Ground Truth Answer: 197
--------------------------------------------------

Problem: Tetrahedron $ABCD$ has $AB=CD=\sqrt{41}$, $AC=BD=\sqrt{80}$, and $BC=AD=\sqrt{89}$. A point $I$ is equidistant from all faces. If this distance is $\frac{m\sqrt{n}}{p}$, find $m+n+p$.

Budget: 900.00 seconds | Deadline: 1775761786.33

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        3             4364             8              0    0.464     104
1        7             4737             7              0    0.480     104
2        8             5686            12              0    0.467     104
3        2             5777            15              0    0.524     104

   Answer  Votes  Score
0     104      4  8.285

Final Answer: 104


[Problem 18 Result]
Model Predicted: 104
Status: ❌ INCORRECT
==================================================

==================================================
TESTING PROBLEM 19
Statement: Triangle $ABC$ is inscribed in $\omega$. Tangents to $\omega$ at $B, C$ intersect at $D$. $AD$ intersects $\omega$ at $P$. If $AB=5, BC=9, AC=10$, and $AP=m/n$, find $m+n$.
Ground Truth Answer: 113
--------------------------------------------------

Problem: Triangle $ABC$ is inscribed in $\omega$. Tangents to $\omega$ at $B, C$ intersect at $D$. $AD$ intersects $\omega$ at $P$. If $AB=5, BC=9, AC=10$, and $AP=m/n$, find $m+n$.

Budget: 900.00 seconds | Deadline: 1775761843.49

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7             3211             9              0    0.619     113
1        8             4257            14              0    0.725     113
2        6             5055             9              1    0.795     113
3        3            10151            19              0    0.686     113

   Answer  Votes  Score
0     113      4  5.711

Final Answer: 113


[Problem 19 Result]
Model Predicted: 113
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 20
Statement: Among the 900 residents of Aimeville, 195 own a diamond ring, 367 own golf clubs, and 562 own a spade. All own candy hearts. 437 own exactly two things, and 234 own exactly three. Find the number who own all four.
Ground Truth Answer: 73
--------------------------------------------------

Problem: Among the 900 residents of Aimeville, 195 own a diamond ring, 367 own golf clubs, and 562 own a spade. All own candy hearts. 437 own exactly two things, and 234 own exactly three. Find the number who own all four.

Budget: 900.00 seconds | Deadline: 1775761938.06

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        4             1613             2              0    0.528      73
1        1             2389             2              0    0.483      73
2        7             2731             1              0    0.638      73
3        2             2985             1              0    0.609      73

   Answer  Votes  Score
0      73      4  7.172

Final Answer: 73


[Problem 20 Result]
Model Predicted: 73
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 21
Statement: A list of positive integers has sum 30 and unique mode 9. The median is a positive integer that does not appear in the list. Find the sum of the squares of all items in the list.
Ground Truth Answer: 236
--------------------------------------------------

Problem: A list of positive integers has sum 30 and unique mode 9. The median is a positive integer that does not appear in the list. Find the sum of the squares of all items in the list.

Budget: 900.00 seconds | Deadline: 1775761967.36

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        5             1827             3              0    0.786     236
1        6             1955             2              0    0.783     236
2        7             2291             2              0    0.787     236
3        3             2298             4              1    0.755     236

   Answer  Votes  Score
0     236      4  5.144

Final Answer: 236


[Problem 21 Result]
Model Predicted: 236
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 22
Statement: Find the number of ways to place a digit in each cell of a $2 \times 3$ grid so the sum of the two 3-digit numbers reading left to right is 999, and the sum of the three 2-digit numbers reading top to bottom is 99.
Ground Truth Answer: 236
--------------------------------------------------

Problem: Find the number of ways to place a digit in each cell of a $2 \times 3$ grid so the sum of the two 3-digit numbers reading left to right is 999, and the sum of the three 2-digit numbers reading top to bottom is 99.

Budget: 900.00 seconds | Deadline: 1775761990.52

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6             3514             1              0    0.742      21
1        5             3882             1              0    0.604      21
2        2             4419             2              0    0.834      21
3        4             4927             7              0    0.649      21

   Answer  Votes  Score
0      21      4  5.743

Final Answer: 21


[Problem 22 Result]
Model Predicted: 21
Status: ❌ INCORRECT
==================================================

==================================================
TESTING PROBLEM 23
Statement: Positive real numbers $x, y, z$ satisfy $\log_2(x/yz)=1/2$, $\log_2(y/xz)=1/3$, and $\log_2(z/xy)=1/4$. If $|\log_2(x^4 y^3 z^2)| = m/n$, find $m+n$.
Ground Truth Answer: 33
--------------------------------------------------

Problem: Positive real numbers $x, y, z$ satisfy $\log_2(x/yz)=1/2$, $\log_2(y/xz)=1/3$, and $\log_2(z/xy)=1/4$. If $|\log_2(x^4 y^3 z^2)| = m/n$, find $m+n$.

Budget: 900.00 seconds | Deadline: 1775762039.10

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7             1207             3              0    0.463      33
1        8             1477             4              0    0.488      33
2        2             1810             3              0    0.398      33
3        6             2116             1              0    0.447      33

   Answer  Votes  Score
0      33      4  8.963

Final Answer: 33


[Problem 23 Result]
Model Predicted: 33
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 24
Statement: Hexagon $ABCDEF$ is convex equilateral with opposite sides parallel. Side extensions of $AB, CD, EF$ form a triangle with side lengths 200, 240, and 300. Find the side length of the hexagon.
Ground Truth Answer: 80
--------------------------------------------------

Problem: Hexagon $ABCDEF$ is convex equilateral with opposite sides parallel. Side extensions of $AB, CD, EF$ form a triangle with side lengths 200, 240, and 300. Find the side length of the hexagon.

Budget: 900.00 seconds | Deadline: 1775762059.37

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        5            12843             8              0    0.698      80
1        2            12838            20              0    0.591      80
2        7            19839            22              2    0.662      80
3        6            24146            28              1    0.633      80

   Answer  Votes  Score
0      80      4  6.215

Final Answer: 80


[Problem 24 Result]
Model Predicted: 80
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 25
Statement: Alice chooses set $A$ of positive integers. Bob lists all finite nonempty sets $B$ where $\max(B) \in A$. Bob's list has 2024 sets. Find the sum of the elements of $A$.
Ground Truth Answer: 55
--------------------------------------------------

Problem: Alice chooses set $A$ of positive integers. Bob lists all finite nonempty sets $B$ where $\max(B) \in A$. Bob's list has 2024 sets. Find the sum of the elements of $A$.

Budget: 900.00 seconds | Deadline: 1775762304.20

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7             1539             2              0    0.673      55
1        2             1686             3              0    0.738      55
2        5             1969             1              0    0.601      55
3        6             1972             4              0    0.642      55

   Answer  Votes  Score
0      55      4  6.063

Final Answer: 55


[Problem 25 Result]
Model Predicted: 55
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 26
Statement: Let $N$ be the greatest four-digit integer such that whenever one digit is changed to 1, the result is divisible by 7. If $Q$ and $R$ are the quotient and remainder when $N$ is divided by 1000, find $Q+R$.
Ground Truth Answer: 699
--------------------------------------------------

Problem: Let $N$ be the greatest four-digit integer such that whenever one digit is changed to 1, the result is divisible by 7. If $Q$ and $R$ are the quotient and remainder when $N$ is divided by 1000, find $Q+R$.

Budget: 900.00 seconds | Deadline: 1775762323.64

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        3             2496             1              0    0.534     699
1        8             2744             3              0    0.540     699
2        2             3598             5              0    0.449     699
3        5             3672             2              0    0.490     699

   Answer  Votes  Score
0     699      4  7.992

Final Answer: 699


[Problem 26 Result]
Model Predicted: 699
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 27
Statement: Find the number of triples of nonnegative integers $(a, b, c)$ satisfying $a + b + c = 300$ and $a^2 b + a^2 c + b^2 a + b^2 c + c^2 a + c^2 b = 6,000,000$.
Ground Truth Answer: 601
--------------------------------------------------

Problem: Find the number of triples of nonnegative integers $(a, b, c)$ satisfying $a + b + c = 300$ and $a^2 b + a^2 c + b^2 a + b^2 c + c^2 a + c^2 b = 6,000,000$.

Budget: 900.00 seconds | Deadline: 1775762358.49

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6             3739            10              0    0.602     601
1        3             3908             5              0    0.619     601
2        2             4224             6              0    0.503     601
3        8             4712             6              0    0.616     601

   Answer  Votes  Score
0     601      4  6.886

Final Answer: 601


[Problem 27 Result]
Model Predicted: 601
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 28
Statement: Let $b \geq 2$. Call a positive integer $b$-eautiful if it has exactly two digits in base $b$ that sum to $\sqrt{n}$. Find the least integer $b$ for which there are more than ten $b$-eautiful integers.
Ground Truth Answer: 211
--------------------------------------------------

Problem: Let $b \geq 2$. Call a positive integer $b$-eautiful if it has exactly two digits in base $b$ that sum to $\sqrt{n}$. Find the least integer $b$ for which there are more than ten $b$-eautiful integers.

Budget: 900.00 seconds | Deadline: 1775762404.92

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6             5754             3              0    0.701     211
1        1             6358             9              0    0.644     211
2        5             6818            11              0    0.677     211
3        7             7718             4              1    0.656     211

   Answer  Votes  Score
0     211      4  5.982

Final Answer: 211


[Problem 28 Result]
Model Predicted: 211
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 29
Statement: Find the number of rectangles formed inside a regular 12-gon where each side lies on either a side or a diagonal of the dodecagon.
Ground Truth Answer: 315
--------------------------------------------------

Problem: Find the number of rectangles formed inside a regular 12-gon where each side lies on either a side or a diagonal of the dodecagon.

Budget: 900.00 seconds | Deadline: 1775762480.57

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        1             4511             1              0    0.852      15
1        6            20218            27              2    0.741     975
2        3            23300            31              2    0.715     315
3        4            23020            22              4    0.828     975
4        7            35774            69             11    0.590     315
5        5            38125            47              5    0.732     315
6        2            43618            55              8    0.697     834
7        8            48770            82              3    0.694     315

   Answer  Votes  Score
0     315      4  5.899
1     975      2  2.558
2     834      1  1.434
3      15      1  1.174

Final Answer: 315


[Problem 29 Result]
Model Predicted: 315
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 30
Statement: Five men and nine women stand in a circle. The probability that every man stands diametrically opposite a woman is $m/n$. Find $m+n$.
Ground Truth Answer: 191
--------------------------------------------------

Problem: Five men and nine women stand in a circle. The probability that every man stands diametrically opposite a woman is $m/n$. Find $m+n$.

Budget: 900.00 seconds | Deadline: 1775762938.24

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        4             2378             6              0    0.880     191
1        7             2521             4              0    0.874     191
2        1             3000             7              0    0.701     191
3        6             3475             9              0    0.790     191

   Answer  Votes  Score
0     191      4  4.974

Final Answer: 191


[Problem 30 Result]
Model Predicted: 191
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 31
Statement: Real numbers $b \neq 1$ and $n$ satisfy $\sqrt{\log_b n} = \log_b \sqrt{n}$ and $b \cdot \log_b n = \log_b (bn)$. If $n=j/k$, find $j+k$.
Ground Truth Answer: 881
--------------------------------------------------

Problem: Real numbers $b \neq 1$ and $n$ satisfy $\sqrt{\log_b n} = \log_b \sqrt{n}$ and $b \cdot \log_b n = \log_b (bn)$. If $n=j/k$, find $j+k$.

Budget: 900.00 seconds | Deadline: 1775762972.99

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6             1001             0              0    0.693     881
1        4             1067             1              0    0.568     881
2        5             1184             2              0    0.606     881
3        7             1350             1              0    0.680     881

   Answer  Votes  Score
0     881      4  6.322

Final Answer: 881


[Problem 31 Result]
Model Predicted: 881
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 32
Statement: A plane contains 40 lines, no 2 parallel. There are points where 3, 4, 5, or 6 lines intersect. Find the number of points where exactly 2 lines intersect.
Ground Truth Answer: 607
--------------------------------------------------

Problem: A plane contains 40 lines, no 2 parallel. There are points where 3, 4, 5, or 6 lines intersect. Find the number of points where exactly 2 lines intersect.

Budget: 900.00 seconds | Deadline: 1775762990.92

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        3             4601             0              0    0.700     607
1        6             4601             0              0    0.840     746
2        1             5201             0              0    0.804     746
3        5             9201             0              0    0.836     746
4        8             9201             0              0    0.743     746

   Answer  Votes  Score
0     746      4  4.975
1     607      1  1.428

Final Answer: 746


[Problem 32 Result]
Model Predicted: 746
Status: ❌ INCORRECT
==================================================

==================================================
TESTING PROBLEM 33
Statement: The sum of all positive integers $m$ such that $13!/m$ is a perfect square is $2^a 3^b 5^c 7^d 11^e 13^f$. Find $a+b+c+d+e+f$.
Ground Truth Answer: 12
--------------------------------------------------

Problem: The sum of all positive integers $m$ such that $13!/m$ is a perfect square is $2^a 3^b 5^c 7^d 11^e 13^f$. Find $a+b+c+d+e+f$.

Budget: 900.00 seconds | Deadline: 1775763074.07

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        5             2079             6              0    0.569      12
1        3             2569             6              0    0.610      12
2        6             2994             9              0    0.291      12
3        8             3044             7              3    0.434      12

   Answer  Votes  Score
0      12      4  9.131

Final Answer: 12


[Problem 33 Result]
Model Predicted: 12
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 34
Statement: Point $P$ is on the circumcircle of square $ABCD$ such that $PA \cdot PC = 56$ and $PB \cdot PD = 90$. Find the area of the square.
Ground Truth Answer: 106
--------------------------------------------------

Problem: Point $P$ is on the circumcircle of square $ABCD$ such that $PA \cdot PC = 56$ and $PB \cdot PD = 90$. Find the area of the square.

Budget: 900.00 seconds | Deadline: 1775763103.83

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        3             3400             2              0    0.642     106
1        8             3361             7              0    0.584     106
2        5             3979             4              0    0.553     106
3        2             4137             2              0    0.536     106

   Answer  Votes  Score
0     106      4  6.947

Final Answer: 106


[Problem 34 Result]
Model Predicted: 106
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 35
Statement: Alice knows 3 red and 3 black cards revealed in random order. Alice guesses color before each. If playing optimally, the expected correct guesses is $m/n$. Find $m+n$.
Ground Truth Answer: 51
--------------------------------------------------

Problem: Alice knows 3 red and 3 black cards revealed in random order. Alice guesses color before each. If playing optimally, the expected correct guesses is $m/n$. Find $m+n$.

Budget: 900.00 seconds | Deadline: 1775763142.83

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6             1613             3              1    0.714      51
1        2             2558             3              0    0.794      51
2        7             2569             5              0    0.772      51
3        1             2678             2              0    0.549      51

   Answer  Votes  Score
0      51      4  5.777

Final Answer: 51


[Problem 35 Result]
Model Predicted: 51
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 36
Statement: Call a positive integer extra-distinct if remainders when divided by 2, 3, 4, 5, and 6 are distinct. Find the number of extra-distinct positive integers less than 1000.
Ground Truth Answer: 49
--------------------------------------------------

Problem: Call a positive integer extra-distinct if remainders when divided by 2, 3, 4, 5, and 6 are distinct. Find the number of extra-distinct positive integers less than 1000.

Budget: 900.00 seconds | Deadline: 1775763170.17

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        5             2785             5              0    0.702      49
1        2             3349             5              0    0.762      49
2        6             4481            11              0    0.655      49
3        7             5521             9              2    0.700      49

   Answer  Votes  Score
0      49      4  5.693

Final Answer: 49


[Problem 36 Result]
Model Predicted: 49
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 37
Statement: Find the number of cubic polynomials $x^3+ax^2+bx+c$ with $a,b,c \in \{-20, \dots, 20\}$ such that there is a unique integer $m \neq 2$ with $p(m)=p(2)$.
Ground Truth Answer: 738
--------------------------------------------------

Problem: Find the number of cubic polynomials $x^3+ax^2+bx+c$ with $a,b,c \in \{-20, \dots, 20\}$ such that there is a unique integer $m \neq 2$ with $p(m)=p(2)$.

Budget: 900.00 seconds | Deadline: 1775763223.30

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6             8191             8              0    0.666     738
1        5             7953             5              0    0.705     738
2        2             9912             6              0    0.639    <NA>
3        4            10060             8              0    0.655    <NA>
4        8            11065            11              0    0.619    <NA>
5        1            12126            10              0    0.639    <NA>
6        7            12421            12              0    0.660     738
7        3            13964            19              2    0.685     738

   Answer  Votes  Score
0     738      4  5.896

Final Answer: 738


[Problem 37 Result]
Model Predicted: 738
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 38
Statement: Find $a+U$ for the unique $a$ where $U = \sum_{n=1}^{2023} \lfloor (n^2-na)/5 \rfloor$ is an integer strictly between -1000 and 1000.
Ground Truth Answer: 944
--------------------------------------------------

Problem: Find $a+U$ for the unique $a$ where $U = \sum_{n=1}^{2023} \lfloor (n^2-na)/5 \rfloor$ is an integer strictly between -1000 and 1000.

Budget: 900.00 seconds | Deadline: 1775763352.06

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        3             1238             3              1    0.752     944
1        6             2182             3              0    0.570     944
2        4             3868             7              0    0.556     944
3        5             4238            11              0    0.590     944

   Answer  Votes  Score
0     944      4  6.577

Final Answer: 944


[Problem 38 Result]
Model Predicted: 944
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 39
Statement: Each face of two noncongruent parallelepipeds is a rhombus with diagonals $\sqrt{21}$ and $\sqrt{31}$. If the volume ratio is $m/n$, find $m+n$.
Ground Truth Answer: 125
--------------------------------------------------

Problem: Each face of two noncongruent parallelepipeds is a rhombus with diagonals $\sqrt{21}$ and $\sqrt{31}$. If the volume ratio is $m/n$, find $m+n$.

Budget: 900.00 seconds | Deadline: 1775763396.15

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6             5397             8              0    0.644     125
1        2             5915             5              0    0.597     125
2        1             6917             5              0    0.628     125
3        5             8084             6              0    0.663     125

   Answer  Votes  Score
0     125      4  6.327

Final Answer: 125


[Problem 39 Result]
Model Predicted: 125
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 40
Statement: Find the greatest integer less than 1000 that is a palindrome in both base 10 and base 8.
Ground Truth Answer: 585
--------------------------------------------------

Problem: Find the greatest integer less than 1000 that is a palindrome in both base 10 and base 8.

Budget: 900.00 seconds | Deadline: 1775763472.87

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7              714             2              0    0.807     585
1        6             1028             4              0    0.708     585
2        4             1043             5              0    0.654     585
3        2             1148             4              0    0.760     585

   Answer  Votes  Score
0     585      4  5.495

Final Answer: 585


[Problem 40 Result]
Model Predicted: 585
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 41
Statement: A region is formed by three unit squares in an L-shape. Two points are chosen randomly. Find $m+n$ if the probability their midpoint is inside the region is $m/n$.
Ground Truth Answer: 35
--------------------------------------------------

Problem: A region is formed by three unit squares in an L-shape. Two points are chosen randomly. Find $m+n$ if the probability their midpoint is inside the region is $m/n$.

Budget: 900.00 seconds | Deadline: 1775763485.28

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        5             5855             3              0    0.664      35
1        7             7401             1              0    0.650      35
2        8             6953             2              0    0.682      35
3        2             7964             4              0    0.641      35

   Answer  Votes  Score
0      35      4  6.071

Final Answer: 35


[Problem 41 Result]
Model Predicted: 35
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 42
Statement: Each vertex of a regular 12-gon is colored red or blue. Find the number of colorings where no four vertices of the same color form a rectangle.
Ground Truth Answer: 928
--------------------------------------------------

Problem: Each vertex of a regular 12-gon is colored red or blue. Find the number of colorings where no four vertices of the same color form a rectangle.

Budget: 900.00 seconds | Deadline: 1775763561.76

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        5             2773             1              0    0.807     928
1        7             2953             2              0    0.760     928
2        3             3254             1              0    0.639     928
3        1             3720             1              0    0.700     928

   Answer  Votes  Score
0     928      4   5.55

Final Answer: 928


[Problem 42 Result]
Model Predicted: 928
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 43
Statement: Let $\omega$ be a 7th root of unity. Find the value of the product $\prod_{k=0}^6 (\omega^{3k} + \omega^k + 1)$.
Ground Truth Answer: 24
--------------------------------------------------

Problem: Let $\omega$ be a 7th root of unity. Find the value of the product $\prod_{k=0}^6 (\omega^{3k} + \omega^k + 1)$.

Budget: 900.00 seconds | Deadline: 1775763597.08

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        2             1806             2              0    0.623      24
1        4             2316             3              0    0.677      24
2        3             2682             3              0    0.684      24
3        7             3045             5              1    0.581      24

   Answer  Votes  Score
0      24      4  6.266

Final Answer: 24


[Problem 43 Result]
Model Predicted: 24
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 44
Statement: Circles $\omega_1, \omega_2$ intersect at $P, Q$. Parallel line $AB$ through $P$ forms trapezoid $XABY$. If $PX=10, PY=14, PQ=5$, find $m+n$ if the area is $m\sqrt{n}$.
Ground Truth Answer: 33
--------------------------------------------------

Problem: Circles $\omega_1, \omega_2$ intersect at $P, Q$. Parallel line $AB$ through $P$ forms trapezoid $XABY$. If $PX=10, PY=14, PQ=5$, find $m+n$ if the area is $m\sqrt{n}$.

Budget: 900.00 seconds | Deadline: 1775763626.48

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        4            28879             6              0    0.798     121
1        7            47654            36              1    0.695     121
2        6            49521            47              3    0.708      40
3        3            56416            85             21    0.652    <NA>
4        1            57258            82             10    0.626    <NA>
5        5            58897            65              7    0.576    <NA>
6        8            60707            54              4    0.646    <NA>
7        2            60038            76              4    0.631    <NA>

   Answer  Votes  Score
0     121      2  2.691
1      40      1  1.412

Final Answer: 121


[Problem 44 Result]
Model Predicted: 121
Status: ❌ INCORRECT
==================================================

==================================================
TESTING PROBLEM 45
Statement: For positive integer $n$, let $a_n$ be the least multiple of 23 with $a_n \equiv 1 \pmod{2^n}$. Find the number of $n \leq 1000$ such that $a_n = a_{n+1}$.
Ground Truth Answer: 363
--------------------------------------------------

Problem: For positive integer $n$, let $a_n$ be the least multiple of 23 with $a_n \equiv 1 \pmod{2^n}$. Find the number of $n \leq 1000$ such that $a_n = a_{n+1}$.

Budget: 900.00 seconds | Deadline: 1775764353.72

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        8             4917             5              0    0.710     363
1        3             6522            15              0    0.589     363
2        5             6781             6              0    0.575     363
3        6             7269             4              0    0.696     363

   Answer  Votes  Score
0     363      4  6.281

Final Answer: 363


[Problem 45 Result]
Model Predicted: 363
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 46
Statement: Right square pyramid volume 54 has base side 6. If vertices lie on a sphere of radius $m/n$, find $m+n$.
Ground Truth Answer: 21
--------------------------------------------------

Problem: Right square pyramid volume 54 has base side 6. If vertices lie on a sphere of radius $m/n$, find $m+n$.

Budget: 900.00 seconds | Deadline: 1775764424.72

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        4             1521             0              0    0.617      21
1        5             1671             2              0    0.634      21
2        2             1695             3              0    0.657      21
3        1             1729             1              0    0.600      21

   Answer  Votes  Score
0      21      4  6.385

Final Answer: 21


[Problem 46 Result]
Model Predicted: 21
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 47
Statement: Find the least value of $a+b$ for real $a>4, b>1$ satisfying $x^2/a^2 + y^2/(a^2-16) = (x-20)^2/(b^2-1) + (y-11)^2/b^2 = 1$.
Ground Truth Answer: 23
--------------------------------------------------

Problem: Find the least value of $a+b$ for real $a>4, b>1$ satisfying $x^2/a^2 + y^2/(a^2-16) = (x-20)^2/(b^2-1) + (y-11)^2/b^2 = 1$.

Budget: 900.00 seconds | Deadline: 1775764441.89

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        4            11187             5              0    0.640      23
1        3            13384            15              1    0.624      23
2        7            13076            14              4    0.562      23
3        1            14197            17              5    0.530      23

   Answer  Votes  Score
0      23      4  6.833

Final Answer: 23


[Problem 47 Result]
Model Predicted: 23
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 48
Statement: Twenty points on a circle are labeled 1-20. Segments are drawn between points whose labels differ by a prime. Find the number of triangles formed.
Ground Truth Answer: 72
--------------------------------------------------

Problem: Twenty points on a circle are labeled 1-20. Segments are drawn between points whose labels differ by a prime. Find the number of triangles formed.

Budget: 900.00 seconds | Deadline: 1775764612.95

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        5             2635             3              0    0.867      72
1        7             2720             3              0    0.764      72
2        6             3273             2              0    0.686      72
3        2             3692             5              0    0.817      72

   Answer  Votes  Score
0      72      4  5.144

Final Answer: 72


[Problem 48 Result]
Model Predicted: 72
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 49
Statement: Find the remainder when $N$ is divided by 1000, where $N$ is the number of sequences of 144 independent hand movements on an analog clock returning to 12.
Ground Truth Answer: 608
--------------------------------------------------

Problem: Find the remainder when $N$ is divided by 1000, where $N$ is the number of sequences of 144 independent hand movements on an analog clock returning to 12.

Budget: 900.00 seconds | Deadline: 1775764648.47

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        3             2998             5              0    0.910     528
1        4             4055             8              0    0.799     950
2        8             4703             4              0    0.810     950
3        7             4869             5              0    0.864     528
4        1             5116             8              1    0.791     528
5        5             5484             5              0    0.693     950
6        6             5556             7              0    0.745     921
7        2             6110            10              2    0.801     950

   Answer  Votes  Score
0     950      4  5.177
1     528      3  3.520
2     921      1  1.343

Final Answer: 950


[Problem 49 Result]
Model Predicted: 950
Status: ❌ INCORRECT
==================================================

==================================================
TESTING PROBLEM 50
Statement: What is the maximum number of terms in an arithmetic sequence of primes with a common difference of 6?
Ground Truth Answer: 5
--------------------------------------------------

Problem: What is the maximum number of terms in an arithmetic sequence of primes with a common difference of 6?

Budget: 900.00 seconds | Deadline: 1775764703.05

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7             2331             2              0    0.720       5
1        3             2624             1              0    0.734       5
2        1             2587             1              0    0.816       5
3        5             2811             1              0    0.743       5

   Answer  Votes  Score
0       5      4  5.322

Final Answer: 5


[Problem 50 Result]
Model Predicted: 5
Status: ✅ CORRECT
==================================================

    idx  prediction  ground_truth  correct
0     1         336           336     True
1     2       32951         32951     True
2     3       24237         21818    False
3     4       32193         32193     True
4     5       57447         57447     True
5     6        8687          8687     True
6     7          50            50     True
7     8         580           580     True
8     9         520           520     True
9    10         160           160     True
10   11         204           204     True
11   12        1778            25    False
12   13         809           809     True
13   14         116           116     True
14   15         104           104     True
15   16         294           294     True
16   17         197           540    False
17   18         104           197    False
18   19         113           113     True
19   20          73            73     True
20   21         236           236     True
21   22          21           236    False
22   23          33            33     True
23   24          80            80     True
24   25          55            55     True
25   26         699           699     True
26   27         601           601     True
27   28         211           211     True
28   29         315           315     True
29   30         191           191     True
30   31         881           881     True
31   32         746           607    False
32   33          12            12     True
33   34         106           106     True
34   35          51            51     True
35   36          49            49     True
36   37         738           738     True
37   38         944           944     True
38   39         125           125     True
39   40         585           585     True
40   41          35            35     True
41   42         928           928     True
42   43          24            24     True
43   44         121            33    False
44   45         363           363     True
45   46          21            21     True
46   47          23            23     True
47   48          72            72     True
48   49         950           608    False
49   50           5             5     True

Overall Accuracy: 84.00%

In [22]:
def predict(id_: pl.DataFrame, question: pl.DataFrame, answer: Optional[pl.DataFrame] = None) -> pl.DataFrame:
    
    id_value = id_.item(0)
    question_text = question.item(0)
    
    gc.disable()
    
    final_answer = solver.solve_problem(question_text)
    
    gc.enable()
    gc.collect()
    
    return pl.DataFrame({'id': id_value, 'answer': final_answer})

In [23]:
inference_server = kaggle_evaluation.aimo_3_inference_server.AIMO3InferenceServer(predict)

if os.getenv('KAGGLE_IS_COMPETITION_RERUN'):
    inference_server.serve()
    
else:
    inference_server.run_local_gateway(
        ('/kaggle/input/competitions/ai-mathematical-olympiad-progress-prize-3/test.csv',)
    )

Problem: What is $0\times10$?

Budget: 900.00 seconds | Deadline: 1775764730.87

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        4               88             0              0    0.535       0
1        8              103             0              0    0.594       0
2        7              109             0              0    0.579       0
3        3              121             0              0    0.662       0

   Answer  Votes  Score
0       0      4  6.788

Final Answer: 0


Problem: Solve $4+x=4$ for $x$.

Budget: 900.00 seconds | Deadline: 1775764732.77

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        2              142             0              0    0.595       0
1        7              149             0              0    0.631       0
2        6              151             0              0    0.557       0
3        3              154             0              0    0.616       0

   Answer  Votes  Score
0       0      4  6.687

Final Answer: 0


Problem: What is $1-1$?

Budget: 900.00 seconds | Deadline: 1775764734.75

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        1               96             0              0    0.560       0
1        5              121             0              0    0.658       0
2        6              127             0              0    0.674       0
3        4              125             0              0    0.563       0

   Answer  Votes  Score
0       0      4  6.567

Final Answer: 0